image: "node:lts-alpine"
stages:
  - build
  - release
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/
    - .cache/

deploy_to_s3:
  stage: build
  before_script:
    - apk add --no-cache aws-cli
  script:
    - npm ci --cache .npm --prefer-offline
    - echo "Deploy to aws S3"
    - GATSBY_ACTIVE_ENV=development ./node_modules/.bin/gatsby build --prefix-paths
    - ./node_modules/.bin/gatsby-plugin-s3 deploy --yes
    - aws cloudfront create-invalidation --distribution-id E151NETYZO2LSM --paths "/*"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  tags:
    - docker

create_buikd:
  stage: release
  before_script:
    - apk add --no-cache aws-cli
  script:
    - npm ci --cache .npm --prefer-offline
    - echo "Create release build"
    - ./node_modules/.bin/gatsby build --prefix-paths
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  tags:
    - docker