image: "circleci/aws-cli:2-node"
stages:
  - deploy
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/
    - .cache/

deploy_to_s3:
  stage: deploy
  script:
    - npm ci --cache .npm --prefer-offline
    - echo "Deploy to aws S3"
    - GATSBY_ACTIVE_ENV=development ./node_modules/.bin/gatsby build --prefix-paths
    - ./node_modules/.bin/gatsby-plugin-s3 deploy --yes
    - aws cloudfront create-invalidation --distribution-id E151NETYZO2LSM
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  tags:
    - docker