image: "amazon/aws-cli"
stages:
  - deploy
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/
    - .cache/

deploy_to_s3:
  stage: deploy
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    AWS_REGION: $AWS_REGION
  before_script:
    - curl -sL https://deb.nodesource.com/setup_16.x | bash -
    - apt-get install -y nodejs
    - eval $(aws ecr get-login --no-include-email --region $AWS_REGION | sed 's|https://||')
  script:
    - npm ci --cache .npm --prefer-offline
    - echo "Deploy to aws S3"
    - GATSBY_ACTIVE_ENV=development ./node_modules/.bin/gatsby build --prefix-paths
    - ./node_modules/.bin/gatsby-plugin-s3 deploy --yes
    - aws cloudfront create-invalidation --distribution-id E151NETYZO2LSM --paths "/*"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  tags:
    - docker