image: "node:lts-alpine"
stages:
  - build
  - deploy
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .cache/
    - public/
npm:install:
  stage: build
  script:
    - npm ci
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_MERGE_REQUEST_ID
  tags:
    - docker

deploy_to_s3:
  stage: deploy
  image: amazon/aws-cli
  needs:
    - npm:install
  script:
    - echo "Deploy to aws S3"
    - ./node_modules/.bin/gatsby build --prefix-paths
    - ./node_modules/.bin/gatsby-plugin-s3 deploy
  variables:
    PAGES_PREFIX: ""  # No prefix by default (master)

  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  tags:
    - docker