image: "node:lts-alpine"
stages:
  - build
#  - test
  - deploy
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .cache/
    - public/
npm:install:
  stage: build
  script:
    - npm ci
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_MERGE_REQUEST_ID
  tags:
    - docker
#test:unit:
#  stage: test
#  needs: ["npm:install"]
#  script:
#    - npm run test:unit
#  rules:
#    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
#    - if: $CI_MERGE_REQUEST_ID
#  tags:
#    - docker
#test:gatsby:
#  stage: test
#  needs: ["npm:install"]
#  script:
#    - ./node_modules/.bin/gatsby info
#  rules:
#    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
#    - if: $CI_MERGE_REQUEST_ID
#  tags:
#    - docker
pages:
  stage: deploy
  needs:
    - npm:install
#    - test:unit
#    - test:gatsby
  script:
    - echo "Pages accessible through ${CI_PAGES_URL}/${PAGES_PREFIX}"
    - ./node_modules/.bin/gatsby build --prefix-paths
  variables:
    PAGES_PREFIX: ""  # No prefix by default (master)
  pages:
    path_prefix: "$PAGES_PREFIX"
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  tags:
    - docker