import React from 'react';
export const ContactDetails = () => {
    return (React.createElement("div", { className: "w-[1227px] h-[294.14px] relative" },
        React.createElement("div", { className: "w-[591px] left-0 top-[43px] absolute" },
            React.createElement("span", { className: "text-[#cc0000] text-[66px] font-normal font-['Helvetica'] leading-[73px]" }, "it\u2019s time"),
            React.createElement("span", { className: "text-[#002d9a] text-[66px] font-normal font-['Helvetica'] leading-[73px]" },
                ' ',
                "to take your digital experiences to the next level.")),
        React.createElement("div", { className: "w-[472px] h-56 left-[755px] top-[32px] absolute" },
            React.createElement("div", { className: "w-[472px] h-56 left-0 top-0 absolute bg-neutral-200" }),
            React.createElement("div", { className: "left-[131px] top-[68px] absolute" },
                React.createElement("span", { className: "text-[#002d9a] text-lg font-bold font-['Helvetica Neue']" }, "800-460-6494"),
                React.createElement("span", { className: "text-black text-lg font-bold font-['Helvetica Neue']" }, ' '),
                React.createElement("span", { className: "text-black text-lg font-normal font-['Helvetica Neue']" },
                    ' ',
                    "|",
                    ' '),
                React.createElement("span", { className: "text-[#002d9a] text-lg font-normal font-['Helvetica Neue']" }, "i"),
                React.createElement("span", { className: "text-[#002d9a] text-lg font-bold font-['Helvetica Neue']" },
                    "nfo@sealworks.com",
                    React.createElement("br", null),
                    React.createElement("br", null)),
                React.createElement("span", { className: "text-black text-lg font-bold font-['Helvetica Neue']" },
                    "Sealworks Interactive Studios",
                    React.createElement("br", null)),
                React.createElement("span", { className: "text-black text-lg font-normal font-['Helvetica Neue']" },
                    "31 w ashland st",
                    React.createElement("br", null),
                    "doylestown, pa 18901"))),
        React.createElement("div", { className: "left-[886px] top-[56px] absolute text-black text-[26px] font-bold font-['Helvetica Neue']" }, "let\u2019s connect"),
        React.createElement("div", { className: "w-[231.90px] h-[294.14px] left-[612px] top-0 absolute" },
            React.createElement("div", { className: "w-[218.92px] h-[273.73px] left-[6.49px] top-[7.42px] absolute" },
                React.createElement("img", { className: "w-[615.12px] h-[446.64px] left-[-193.74px] top-[-68.81px] absolute", src: "https://via.placeholder.com/615x447" })))));
};
